### ISSUE TITLE
Contributor list is missing

### ISSUE THREAD

**Issue by frankrousseau** [cgwire/awesome-cg-vfx-pipeline#34]
Adding the contributor list at the end would be nice for people who added links to this awesome list.

**Comment by loonghao** [comment]
@frankrousseau  About adding the contributor list, I recommend using [all-contributors](https://github.com/all-contributors/all-contributors), Cheers.

**Comment by frankrousseau** [comment]
@all-contributors please add @loonghao for #49

**Comment by frankrousseau** [comment]
@all-contributors please add @loonghao for content

**Comment by frankrousseau** [comment]
Thank you @loonghao, it seems to work fine. Now I just have to copy the Github particpant list there!

**Comment by frankrousseau** [comment]
@all-contributors please add @frankrousseau for content

@all-contributors please add @darkvertex  for content

@all-contributors please add @stilobique for content

**Comment by frankrousseau** [comment]
@all-contributors please add @frankrousseau for content

**Comment by frankrousseau** [comment]
@all-contributors please add @darkvertex for content

**Comment by frankrousseau** [comment]
@all-contributors please add @stilobique for content

**Comment by frankrousseau** [comment]
@all-contributors please add @frankrousseau for content

**Comment by frankrousseau** [comment]
@all-contributors please add @notawhalevfx for content

**Comment by frankrousseau** [comment]
@all-contributors please add @cg-cnu for content

**Comment by frankrousseau** [comment]
@all-contributors please add @stilobique for content

**Comment by frankrousseau** [comment]
@all-contributors please add @bob-white for content

**Comment by frankrousseau** [comment]
@all-contributors please add @bob-white for content

**Comment by frankrousseau** [comment]
@all-contributors please add @theodox for content

**Comment by frankrousseau** [comment]
@all-contributors please add @developer-cube-creative for content

**Comment by frankrousseau** [comment]
@all-contributors please add @tokejepsen for content

**Comment by frankrousseau** [comment]
@all-contributors please add @santosh for content

**Comment by frankrousseau** [comment]
@all-contributors please add @listyque  for content

**Comment by frankrousseau** [comment]
@all-contributors please add @justint for content

**Comment by frankrousseau** [comment]
@all-contributors please add @jtomori for content

**Comment by frankrousseau** [comment]
@all-contributors please add @jfpanisset for content

**Comment by frankrousseau** [comment]
@all-contributors please add @hellozee for content

**Comment by frankrousseau** [comment]
@all-contributors please add @heavyimage for content

**Comment by frankrousseau** [comment]
@all-contributors please add @corentincharron for content

**Comment by frankrousseau** [comment]
@all-contributors please add @artbycrunk for content

**Comment by frankrousseau** [comment]
@all-contributors please add @anvth for content

**Comment by frankrousseau** [comment]
@all-contributors please add @aboellinger for content

**Comment by frankrousseau** [comment]
Done!

**Comment by frankrousseau** [comment]
@all-contributors please add  @mwestphal for content

**Comment by frankrousseau** [comment]
@all-contributors please add @eoyilmaz for content

**Comment by frankrousseau** [comment]
@all-contributors please add @mcoliver for content

**Comment by frankrousseau** [comment]
https://github.com/all-contributors please add @potahto for content

**Comment by frankrousseau** [comment]
@all-contributors please add @potahto for content
