### ISSUE TITLE
OGRE and Minetest

### ISSUE THREAD

**Issue by acs** [cgwire/awesome-cg-vfx-pipeline#50]
Hi guys!

First of all, thank you for this detailed recompilation of Open source projects.

I am missing:

* [OGRE](https://www.ogre3d.org/): Open Source 3D Graphics Engine 
* [Minetest](https://www.minetest.net/): Open source voxel game engine

Also, the Unreal engine is not open source afaik.

Thanks!

**Comment by stilobique** [comment]
Hi @acs !
It is not an **Open Source** list, but a huge compilation about software and more.
I'm look to add OGRE on the list.

**Comment by stilobique** [comment]
I'm make an pull request (#51) with this issue, if @frankrousseau can look to edit the pull request link.
Have a good day !

**Comment by frankrousseau** [comment]
Hi @acs and @stilobique 

I do not agree, it's mainly open source software. We started this list because we found it hard to find CGI/VFX open source tools.
About Unreal Engine, you can find the source code here: https://www.unrealengine.com/en-US/ue4-on-github.

**Comment by frankrousseau** [comment]
Thank you @stilobique for the PR!
