### ISSUE TITLE
Gaffer is not an asset manager

### ISSUE THREAD

**Issue by mrpurest** [cgwire/awesome-cg-vfx-pipeline#83]
Gaffer is not an asset manager.

Not sure which category I would place it in but I have recently been using it in place of maya (for lighting), so 3d?

**Comment by frankrousseau** [comment]
Scene assembly?

**Comment by mrpurest** [comment]
I think that would be a better description than "asset manager".

**Comment by stilobique** [comment]
```
Gaffer is a free, open-source, node-based VFX application that enables look developers, lighters, and compositors to easily build, tweak, iterate, and render scenes. Built with flexibility in mind, Gaffer supports in-application scripting in Python and OSL, so VFX artists and technical directors can design shaders, automate processes, and build production workflows.

With hooks in both C++ and Python, Gaffer's readily extensible API provides both professional studios and enthusiasts with the tools to add their own custom modules, nodes, and UI.

The workhorse of the production pipeline at Image Engine Design Inc., Gaffer has been used to build award-winning VFX for shows such as Jurassic World: Fallen Kingdom, Lost in Space, Logan, and Game of Thrones.
```
The description on the web site are veary large ^^ . Not really easy to put it in one case. I think use the description and set a new category `Scene assembly` can be more explicit.

**Comment by Chantology** [comment]
Do I understand it correctly that it's used for look dev, lighting & comp as well? Then it should be in the 3D category? Not an easy decision!

**Comment by stilobique** [comment]
After more reflexion, `Scene Assembly` is not a good description -i think- It's to work on post-production on nodal VFX, but it also to control your rendering, your shading... it's a very large toolbox. I'm push an new entry with a small description inside the DCC software. However, i don't have another software to complete is panel :/ . 

@mrpurest if you have more comment about this choice, don't hesitate to reply !

**Comment by mrpurest** [comment]
I think 3D is the most suitable category.

Its not entirely accurate, but I think its the closest of the existing categories, and I don't think it makes sense for it to be in its own section.

There is a few tools that it would share a category with (katana, clarisse builder?), but of course only gaffer is open source.

**Comment by stilobique** [comment]
> [...]
> Its not entirely accurate, but I think its the closest of the existing categories, and I don't think it makes sense for it to be in its own section.
> [...]
Yes, good point ; make a category with only one entry can be confusing. I'm look to regroup this entry.
Thanks for your comment ;)
