### ISSUE TITLE
Monitoring web services

### ISSUE THREAD

**Issue by stilobique** [cgwire/awesome-cg-vfx-pipeline#85]
Hello world :) .
I'm not sure about the monitoring web services section ; i thinks is not really usefull to keep this entry inside this list. Maybe we can adding a link to another *awesome list* [like a dedicated sys admin list](https://github.com/n1trux/awesome-sysadmin#metric--metric-collection).

Or maybe adding an entry or information to search on an external list.

What do you thinks about that ?

**Comment by frankrousseau** [comment]
Yes, a link would be more efficient. Monitoring web services is not a primary concern for TDs.
