### ISSUE TITLE
Allusion - Open Source Visual Library

### ISSUE THREAD

**Issue by Chantology** [cgwire/awesome-cg-vfx-pipeline#87]
Allusion is for creating image libraries for references. It has a GNU General Public License v3.0 license. 
It's great if you have a huge collection of references and you need to sort them and give tags.  This could be in the asset manager category or in the 2D category. 

Homepage: https://allusion-app.github.io/
Github: https://github.com/allusion-app/Allusion/blob/master/LICENSE 

I will learn how to use Git and make PRs soon!

**Comment by stilobique** [comment]
It's really interesting, 
```Our application was designed to be a complementary tool to PureRef by supporting easy drag and drop between the two. ```

I'm look to add-it.

**Comment by stilobique** [comment]
All right, i'm adding a new category entry call `Board Ref`. I'm adding PureRef, i don't have more Board tools software. 
It's close with this commit `Make a new category` https://github.com/cgwire/awesome-cg-vfx-pipeline/commit/83e1a60c385f649f17bf982aafab1d6aea5e56d2.

**Comment by frankrousseau** [comment]
Great thank you @stilobique!

**Comment by Chantology** [comment]
@stilobique thanks for updating the list. Only note is that Pure-Ref is not open-source.

**Comment by stilobique** [comment]
Yes, i see that :s . I have fix my mistake with a previous commit.
